### ISSUE TITLE
Express Routes

### ISSUE THREAD

**Issue by DanielWGross** [DanielWGross/cardinalRecording#22]
#### Description:
Need to establish different routes for the pages throughout the site.

#### Tasks
- [ ] Clients page should have a GET route to render Client Cards
- [ ] Equipment page should have a GET route to render equipment
- [ ] Contact should have a POST route to submit contact confirmation
- [ ] 404 Route for unknown routes
