### ISSUE TITLE
Add Social Media Links

### ISSUE THREAD

**Issue by DanielWGross** [DanielWGross/cardinalRecording#6]
#### Description:
Replace any "dummy" content with valid links to social media accounts.

#### Relevant Info:
[Facebook](https://www.facebook.com/cardinalrecordings/)
[Soundcloud](https://soundcloud.com/cardinal-recordings)
[Instagram](https://www.instagram.com/cardinalrecordings/?hl=en)
[Email](CardinalRecBooking@gmail.com)

#### Tasks
- [ ] FaceBook link takes you to client FaceBook page
- [ ] SoundCloud link takes you to client SoundCloud page
- [ ] Instagram link takes you to client Instagram Page
- [ ] E-mail link opens up default mail client
